### ISSUE TITLE
incorrectly created pesign-package.spec for packages with non-kmp subpackages

### ISSUE THREAD

**Issue by darix** [openSUSE/pesign-obs-integration#22]
https://build.opensuse.org/package/view_file/multimedia:apps/v4l2loopback/v4l2loopback.spec?expand=1

The list of subpackages is sorted alphabetically and then it takes the package metadata from the first package for the newly created spec file. So if there is any subpackage that starts with a-j then it will grab the metadata from there instead of the kmp packages itself.

In this case it leads to noarch kmp packages. but it would also lead to incorrect descriptions/license/summary and so on.

I really think that the code should query the packages that it will actually sign here.

**Comment by darix** [comment]
If possible we should submit an 15.x update as well so we can release v4l2loopback as an update there.

**Comment by bugfinder** [comment]
created PR 23
https://github.com/openSUSE/pesign-obs-integration/pull/23

**Comment by lcp** [comment]
Merged the patch @bugfinder 
Will create a bug for 15.x for the further update.

**Comment by lcp** [comment]
The bug for sle/opensuse
https://bugzilla.suse.com/show_bug.cgi?id=1180242
